package io.rashed.finance.infrastructure.backup;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Objects;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import io.rashed.finance.application.backup.BackupArchive;
import io.rashed.finance.application.backup.BackupFailedException;
import io.rashed.finance.application.backup.BackupFileNames;
import io.rashed.finance.application.backup.BackupStorage;
import io.rashed.finance.application.settings.SettingKeys;
import io.rashed.finance.application.settings.SettingsProvider;
import io.rashed.finance.common.enums.BackupProvider;

/**
 * Keeps archives on the local filesystem, under the directory named by
 * the {@code BACKUP_DIRECTORY} setting (default {@code storage/backups}).
 *
 * Always available: the directory is created on demand, and a path that
 * cannot be written is reported when the backup runs rather than
 * pre-emptively — the failure message from the filesystem is more useful
 * than a guess.
 */
@Component
public class LocalBackupStorage implements BackupStorage {

    private static final Logger log = LoggerFactory.getLogger(LocalBackupStorage.class);

    private final SettingsProvider settings;

    public LocalBackupStorage(SettingsProvider settings) {
        this.settings = Objects.requireNonNull(settings);
    }

    @Override
    public BackupProvider provider() {
        return BackupProvider.LOCAL;
    }

    @Override
    public boolean isAvailable() {
        return true;
    }

    @Override
    public String unavailableReason() {
        throw new IllegalStateException("Local storage is always available.");
    }

    @Override
    public StoredArchive store(BackupArchive archive) {

        Path directory = backupDirectory();
        Path target = resolve(directory, archive.fileName());

        try {
            Files.createDirectories(directory);
            Files.write(target, archive.content());

            log.info("Wrote backup {} ({} bytes)", target.toAbsolutePath(), archive.size());

            return new StoredArchive(target.toAbsolutePath().toString(), null);

        } catch (IOException ex) {
            throw new BackupFailedException(
                    "Could not write the backup to " + target.toAbsolutePath()
                            + ": " + ex.getMessage(), ex);
        }
    }

    @Override
    public BackupArchive retrieve(StoredArchiveLocation location) {

        Path file = locate(location);

        if (!Files.isRegularFile(file)) {
            throw new BackupFailedException(
                    "Backup file " + file.toAbsolutePath() + " no longer exists.");
        }

        try {
            return BackupArchive.of(
                    location.fileName(),
                    BackupFileNames.formatOf(location.fileName()),
                    Files.readAllBytes(file)
            );

        } catch (IOException ex) {
            throw new BackupFailedException(
                    "Could not read the backup at " + file.toAbsolutePath()
                            + ": " + ex.getMessage(), ex);
        }
    }

    @Override
    public void delete(StoredArchiveLocation location) {

        Path file = locate(location);

        try {
            if (Files.deleteIfExists(file)) {
                log.info("Deleted backup {}", file.toAbsolutePath());
            }

        } catch (IOException ex) {
            throw new BackupFailedException(
                    "Could not delete the backup at " + file.toAbsolutePath()
                            + ": " + ex.getMessage(), ex);
        }
    }

    /**
     * Uses the recorded absolute path when there is one, so an archive
     * still resolves after {@code BACKUP_DIRECTORY} is changed. Falls back
     * to the configured directory for records written without a path.
     */
    private Path locate(StoredArchiveLocation location) {

        if (location.path() != null && !location.path().isBlank()) {
            return Paths.get(location.path());
        }

        return resolve(backupDirectory(), location.fileName());
    }

    private Path backupDirectory() {

        return Paths.get(settings.getString(
                SettingKeys.BACKUP_DIRECTORY,
                SettingKeys.BACKUP_DIRECTORY_FALLBACK
        ));
    }

    /**
     * Joins a file name to the backup directory, refusing anything that
     * would escape it. File names are generated by
     * {@link BackupFileNames#forBackup} today, but a restore-by-name request
     * arrives from the client, and {@code ../../etc/passwd} must not
     * resolve.
     */
    private Path resolve(Path directory, String fileName) {

        Path resolved = directory.resolve(fileName).normalize();

        if (!resolved.startsWith(directory.normalize())) {
            throw new BackupFailedException("Invalid backup file name: " + fileName);
        }

        return resolved;
    }
}
